# Generated by Django 2.1.2 on 2019-06-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mylearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='interview_qa',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mylearning.Topic'),
        ),
        migrations.AlterField(
            model_name='reading_material',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mylearning.Topic'),
        ),
    ]
