# Generated by Django 2.1.2 on 2019-06-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mylearning', '0002_auto_20190617_1928'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interview_qa',
            table='Interview_QA',
        ),
    ]
