# Generated by Django 2.1.2 on 2019-06-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mylearning', '0004_auto_20190621_0138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentRegForm',
            new_name='RegForm',
        ),
    ]
