# Generated by Django 2.1.2 on 2019-06-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mylearning', '0005_auto_20190621_0145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegForm',
            new_name='Reg_Form',
        ),
    ]
