# Generated by Django 2.1.2 on 2019-06-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mylearning', '0007_auto_20190621_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_qa',
            name='question_num',
            field=models.IntegerField(),
        ),
    ]
