# Generated by Django 2.1.2 on 2019-06-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeyard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
