# Generated by Django 2.1.2 on 2020-01-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeyard', '0003_companyservices_contactdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyservices',
            old_name='contact',
            new_name='contact_had',
        ),
        migrations.RenameField(
            model_name='contactdetail',
            old_name='address',
            new_name='address_line',
        ),
        migrations.AlterField(
            model_name='companyservices',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
