# Generated by Django 2.1.2 on 2020-01-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeyard', '0004_auto_20200122_0229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetail',
        ),
    ]
