# Generated by Django 2.1.2 on 2018-10-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(max_length=20)),
                ('book_title', models.CharField(max_length=200)),
                ('book_subject', models.CharField(max_length=200)),
                ('book_publisher', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Donner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(max_length=10)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('Books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Books')),
            ],
        ),
    ]
