# Generated by Django 2.1.2 on 2019-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='share_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companey_name', models.CharField(max_length=50)),
                ('parent_companey', models.CharField(max_length=50)),
                ('share_current_Price', models.IntegerField(max_length=10)),
                ('share_open_Price', models.IntegerField(max_length=10)),
                ('share_close_Price', models.IntegerField(max_length=10)),
                ('trade_volume', models.CharField(max_length=2000)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'share_list',
            },
        ),
    ]
