# Generated by Django 2.1.2 on 2020-01-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketlive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_list',
            name='share_close_Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='share_list',
            name='share_current_Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='share_list',
            name='share_open_Price',
            field=models.IntegerField(),
        ),
    ]
