# Generated by Django 2.1.2 on 2020-02-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Service_Product',
            new_name='company_enquire_name',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='company_name',
            new_name='service_product',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='File',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='Requirements',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='enquire_name',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_number',
            field=models.IntegerField(auto_created=True, unique_for_date=True),
        ),
    ]
