# Generated by Django 2.1.2 on 2020-02-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0002_auto_20200209_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_number',
            field=models.IntegerField(auto_created=True),
        ),
    ]
