# Generated by Django 2.1.2 on 2020-02-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0003_auto_20200209_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='enquiry_number',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='address_location',
            field=models.CharField(max_length=200),
        ),
    ]
