# Generated by Django 2.1.2 on 2020-02-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0004_auto_20200209_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
