# Generated by Django 2.2.9 on 2020-02-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0007_auto_20200210_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
