# Generated by Django 2.2.9 on 2020-02-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0008_auto_20200210_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='image',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
