# Generated by Django 2.2.9 on 2020-02-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0009_auto_20200212_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
