# Generated by Django 2.1.2 on 2020-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0013_auto_20200213_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='id',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enq_num',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='enquiry/files/'),
        ),
    ]
