# Generated by Django 2.1.2 on 2020-02-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0014_auto_20200218_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enq_num',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
