# Generated by Django 2.1.2 on 2020-01-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=True)),
                ('cali_type', models.CharField(max_length=150)),
                ('cali_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
