# Generated by Django 2.1.2 on 2018-10-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_category', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('release_year', models.CharField(max_length=300)),
                ('actor', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
            ],
        ),
    ]
